### PR TITLE
Fix the missing locale name in title

### LINKED ISSUE #404: Title management should not remove locale name
Patterns URLs like https://fr.wordpress.org/patterns/ (correctly) append a localization string to the `<title>` elem, but this is removed via JavaScript.

This behaviour should be removed; the title should not be altered.

### PR DESCRIPTION
**Pull request by outdoor2kode**
This PR
1. Restructure `wporgLocale` to include more locale info:
    a. locale base id
    b. locale display name
2. Fix the logic affected by the restruction
3. Add functions to get the rosetta name (locale display name)

Fixes #404 

### Screencasts
Before:
https://d.pr/v/466P0M
After:
https://d.pr/v/2SsuBI

### How to test the changes in this Pull Request:

1. Go to any rosetta site
2. Open Chrome devTools
3. Search for <title>
4. Check if the locale name is appended

### CODE REVIEW

File: public_html/wp-content/themes/pattern-directory/functions.php [hunk 1]
```diff
@@ -80,7 +106,13 @@ function enqueue_assets() {
 
 		wp_add_inline_script(
 			'wporg-pattern-script',
-			sprintf( "var wporgLocale = '%s';", wp_json_encode( get_locale() ) ),
+			sprintf(
+				"var wporgLocale = JSON.parse( decodeURIComponent( '%s' ) )",
+				rawurlencode( wp_json_encode( array(
+					'baseId' => get_locale(),
```
Comment (StevenDufresne) [inline public_html/wp-content/themes/pattern-directory/functions.php]: I think JavaScript API's call this the `baseName`. I'm not bothered by `baseId` though.

File: public_html/wp-content/themes/pattern-directory/functions.php [hunk 2]
```diff
@@ -36,6 +37,31 @@ function setup() {
...
 }
 
+/**
+ * Determine if the current site is a Rosetta site (e.g., `es-mx.wordpress.org`).
+ *
+ * This returns `false` for `translate.wordpress.org`; it's part of the Rosetta network, but isn't a Rosetta site.
+ *
+ * @return bool
+ */
+function is_rosetta_site() : bool {
```
Comment (StevenDufresne) [inline public_html/wp-content/themes/pattern-directory/functions.php]: I wonder if we could move these rosetta helper functions into a `mu-plugin`?... maybe in the new [`wporg-mu-plugins` repo](https://github.com/WordPress/wporg-mu-plugins). If we needed them in the pattern directory, we are bound to need them elsewhere.

**Review by StevenDufresne — COMMENTED** [review]
Nice! I left a few comments.

I logged a few issues that I found while testing these changes:
https://github.com/WordPress/pattern-directory/issues/464
https://github.com/WordPress/pattern-directory/issues/465

These issues don't have to be solved by this ticket, but it may be worth thinking about them so you don't have to come back?

File: public_html/wp-content/themes/pattern-directory/functions.php (hunk 2 above)
Comment (outdoor2kode) [reply public_html/wp-content/themes/pattern-directory/functions.php]: Good point, it's definitely better to put this kind of function in one place and reuse them. I'll see how to put it together.

Comment (ryelle) [reply public_html/wp-content/themes/pattern-directory/functions.php]: These functions already exist [in the global blocks,](https://github.com/WordPress/wporg-mu-plugins/blob/b1ac446e2305dbd70c1d10950f1dc3f8680461af/mu-plugins/blocks/global-header-footer/blocks.php#L453) so you should be able to use them by pulling in `use function WordPressdotorg\MU_Plugins\Global_Header_Footer\{ get_rosetta_name, is_rosetta_site }`.

A possible improvement (to the mu-plugins project) could be to move the functions out of the blocks folder so it's clear they're not tied to the blocks.

File: public_html/wp-content/themes/pattern-directory/functions.php (hunk 1 above)
Comment (outdoor2kode) [reply public_html/wp-content/themes/pattern-directory/functions.php]: I do like `baseName` more, but after looking into this [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale), I found that in its Parameters and Examples sections, it suggests that `ko-Kore-KR` is different from `ko-KR`. 
The former one is `baseName` and the latter one is `locale identifier` (see the description of tag under [Parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale#parameters) and this [Example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale#basic_usage)). 
So I'll change it to just `id` then. Thanks for bringing this up!

File: public_html/wp-content/themes/pattern-directory/functions.php (hunk 2 above)
Comment (outdoor2kode) [reply public_html/wp-content/themes/pattern-directory/functions.php]: Didn't know those two functions can be pulled in that way here. Thanks!

> A possible improvement (to the mu-plugins project) could be to move the functions out of the blocks folder so it's clear they're not tied to the blocks.

I'll take a look at it. 👀

File: public_html/wp-content/themes/pattern-directory/functions.php (hunk 1 above)
Comment (outdoor2kode) [reply public_html/wp-content/themes/pattern-directory/functions.php]: > So I'll change it to just id then. Thanks for bringing this up!

Done changing.

File: public_html/wp-content/themes/pattern-directory/functions.php (hunk 2 above)
Comment (outdoor2kode) [reply public_html/wp-content/themes/pattern-directory/functions.php]: > These functions already exist [in the global blocks,](https://github.com/WordPress/wporg-mu-plugins/blob/b1ac446e2305dbd70c1d10950f1dc3f8680461af/mu-plugins/blocks/global-header-footer/blocks.php#L453) so you should be able to use them by pulling in use function WordPressdotorg\MU_Plugins\Global_Header_Footer\{ get_rosetta_name, is_rosetta_site }.

Done changing.

> A possible improvement (to the mu-plugins project) could be to move the functions out of the blocks folder so it's clear they're not tied to the blocks.
>> I'll take a look at it. 👀

I've created a new [issue](https://github.com/WordPress/wporg-mu-plugins/issues/191) in the wporg-mu-plugins repo, and I'll keep track of it.

**Comment by renintw** [comment]
> Nice! I left a few comments.
> 
> I logged a few issues that I found while testing these changes: #464 #465
> 
> These issues don't have to be solved by this ticket, but it may be worth thinking about them so you don't have to come back?

I've taken a look at these two issues, and I've assigned them to myself. I'll create another PR for them.


@ryelle @StevenDufresne, please help review the PR again for what I've changed based on your comments, thanks!

**Comment by outdoor2kode** [comment]
> Nice! I left a few comments.
> 
> I logged a few issues that I found while testing these changes: #464 #465
> 
> These issues don't have to be solved by this ticket, but it may be worth thinking about them so you don't have to come back?

I've taken a look at these two issues and have assigned them to myself. I'll create another PR for them.


@ryelle @StevenDufresne, I've made changes based on your comments, please help review them if you got time, thanks!

**Comment by StevenDufresne** [comment]
This LGTM. I'll let @ryelle get the final thought seeing that she also had comments.

**Review by ryelle — APPROVED** [review]
Looks good! The title is updating correctly, and the correct locale is still used when loading patterns 👍🏻
