### PR TITLE
Theme: Fix backwards and forwards navigation state.

### LINKED ISSUE #285: Pattern Navigation: Back button does not update query
Navigating back with the browser back button does not update the page itself.

**To Reproduce**

1. On the homepage, click a category or pagination link - let's pick Columns
2. Now you should be viewing Columns patterns
3. Click back
4. The URL updates in the browser, but the website still shows the Columns category

**Expected behavior**

The query itself should update, and load "All patterns" or whatever the correct previous page was.

**Desktop (please complete the following information):**
Mac & Firefox

### PR DESCRIPTION
**Pull request by StevenDufresne**
This adds a listener for `onpopstate` to the route hook and updates the path when the user triggers navigation using the browser's navigational tools (Shortcut keys, back/forward button).

Fixes #285

### Screenshots
N/A

### How to test the changes in this Pull Request:

1. Visit `/`
2. Click on multiple categories
2. Click the browser back button
3. Expect to go backwards with the selected category with the applicable result sets.

### CODE REVIEW

File: public_html/wp-content/themes/pattern-directory/src/hooks/route.js [hunk 1]
```diff
@@ -58,6 +58,18 @@ export function RouteProvider( { children } ) {
...
+	/**
+	 * Updates the path to the current browser path.
+	 */
+	const setPathOnPop = () => {
+		setPath( document.location.href );
+	};
+
+	useEffect( () => {
+		// When the browser modifies the history, update our path.
+		window.addEventListener( 'popstate', setPathOnPop ); // eslint-disable-line @wordpress/no-global-event-listener
```
Comment (ryelle) [inline public_html/wp-content/themes/pattern-directory/src/hooks/route.js:70]: Should this also [unsubscribe the event listener](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1)?

Comment (StevenDufresne) [reply public_html/wp-content/themes/pattern-directory/src/hooks/route.js:70]: That's a good idea. 90076fe

**Review by ryelle — APPROVED** [review]
