### PR TITLE
Limit front end patterns to site locale

### LINKED ISSUE #273: Theme: Query results show translated patterns side by side.
**Describe the bug**
I'm not sure if it's enclosed in another ticket but I'll add this in case. 

Since we now have translated patterns, the search results are showing translated versions of the same pattern making the pattern list a bit useless.

**To Reproduce**
1. Go to `wordpress.org/patterns`
2. View the result list, expect to see the same patterns in different languages.

**Expected behavior**
We should only see patterns matching our locale.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version July 7, latest :)

### PR DESCRIPTION
**Pull request by iandunn**
This makes it so that Rosetta sites like `es-mx.wordpress.org/patterns` will only display patterns with a `es_MX` locale.

In the future, we may want to include all locales, but weight translated ones higher (see https://github.com/WordPress/pattern-directory/issues/244#issuecomment-871985952), but this is good enough for the initial launch.

Fixes #273

### CODE REVIEW

**Comment by iandunn** [comment]
This kinda works, but I'm guessing it not exactly the way @StevenDufresne or @ryelle would do it. Do y'all have any thoughts?

File: public_html/wp-content/themes/pattern-directory/src/components/patterns/index.js [hunk 1]
```diff
@@ -16,6 +16,11 @@ import { store as patternStore } from '../../store';
 const Patterns = () => {
 	const query = useSelect( ( select ) => select( patternStore ).getCurrentQuery() );
 
+	if ( query ) {
+		query.locale = wporgLocale;
+		// todo why does it still say "loading all patterns"?
```
Comment (StevenDufresne) [inline public_html/wp-content/themes/pattern-directory/src/components/patterns/index.js]: This is happening because it's stuck in an infinite loop.

Move this code into the `QueryMonitor` control. Probably [here](https://github.com/WordPress/pattern-directory/blob/4d05a3f95e556ff4c64db43a9e920e3c544e558a/public_html/wp-content/themes/pattern-directory/src/components/query-monitor/index.js#L60).

**Comment by ryelle** [comment]
I would add the locale to the query at a lower level, in the API request in the resolver itself:

https://github.com/WordPress/pattern-directory/blob/173cd98d161887536a9d2883b8cfbb38e2d06eee/public_html/wp-content/themes/pattern-directory/src/store/resolvers.js#L49

```diff
- path: addQueryArgs( '/wp/v2/wporg-pattern', query ),
+ path: addQueryArgs( '/wp/v2/wporg-pattern', { ...query, locale: wporgLocale } ),
```

This would affect all pattern-grid queries - the main page, categories, authors, and "My Patterns". The only one I could see that being weird on is My Patterns, but I think we can ignore that for now - pattern creation is not ready for public, so the only user that has a My Patterns page is `wordpressdotorg`. (TBH I also think that this would be the expected behavior, I don't think someone who creates a pattern on `ja.wordpress.org/patterns` would expect to see it on `es.wordpress.org/patterns` - but that can be a discussion later)

Going to a pattern directly uses a different resolver/API request, so any locale pattern can be viewed directly, ex: `http://es.wordpress.org/patterns/pattern/two-columns-of-text-with-images-ja/`

File: public_html/wp-content/themes/pattern-directory/src/components/patterns/index.js (hunk 1 above)
Comment (iandunn) [reply public_html/wp-content/themes/pattern-directory/src/components/patterns/index.js]: Thanks!

**Comment by iandunn** [comment]
That sounds good, thanks! Tested this on my w.org sandbox and it's looking good.

**Comment by StevenDufresne** [comment]
> I would add the locale to the query at a lower level, in the API request in the resolver itself:
> 
> https://github.com/WordPress/pattern-directory/blob/173cd98d161887536a9d2883b8cfbb38e2d06eee/public_html/wp-content/themes/pattern-directory/src/store/resolvers.js#L49
> 
> ```diff
> - path: addQueryArgs( '/wp/v2/wporg-pattern', query ),
> + path: addQueryArgs( '/wp/v2/wporg-pattern', { ...query, locale: wporgLocale } ),
> ```

Yep, this works wells too. I suggested the `QueryMonitor` in case we planned to add a locale switcher to the interface. If we did so and it was a non-reload-the-page version, we'd want to pull from the query string. But early days for those kinds of thoughts 👍 .
