### PR TITLE
Patterns: Decode potentially-malformed ampersands in block content

### LINKED ISSUE #488: Encoding in pattern code breaks rawpixel URLs when copy/pasting pattern
Rawpixel URLs are broken when copied in the pattern code (using the "copy" button), because the URL is being over-encoded.

For example, copy [this pattern](https://wordpress.org/patterns/pattern/call-to-action-with-cover-background/), which results in this code:

<details>
<summary>Pattern code</summary>

```html
<!-- wp:cover {"url":"https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd21-021999-534-chim.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=25816d15921707b6523fa40e52efdcac","dimRatio":80,"customOverlayColor":"#4f4523","minHeight":40,"minHeightUnit":"vw","contentPosition":"center center","align":"full","style":{"color":{"duotone":["#000000","#ffffff"]}}} -->
<div class="wp-block-cover alignfull" style="min-height:40vw"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-80 has-background-dim" style="background-color:#4f4523"></span><img class="wp-block-cover__image-background" alt="" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd21-021999-534-chim.jpg?w=1200&amp;h=1200&amp;fit=clip&amp;crop=default&amp;dpr=1&amp;q=75&amp;vib=3&amp;con=3&amp;usm=15&amp;cs=srgb&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=25816d15921707b6523fa40e52efdcac" data-object-fit="cover" /><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"50px","bottom":"50px"}}},"layout":{"inherit":true}} -->
<div class="wp-block-group alignwide" style="padding-top:50px;padding-bottom:50px"><!-- wp:cover {"url":"https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd19-20011.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=6be89633a3b20429853f6d3192649709","dimRatio":20,"overlayColor":"white","minHeight":20,"minHeightUnit":"vw","contentPosition":"center center","isDark":false,"align":"wide"} -->
<div class="wp-block-cover alignwide is-light" style="min-height:20vw"><span aria-hidden="true" class="wp-block-cover__background has-white-background-color has-background-dim-20 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd19-20011.jpg?w=1200&amp;h=1200&amp;fit=clip&amp;crop=default&amp;dpr=1&amp;q=75&amp;vib=3&amp;con=3&amp;usm=15&amp;cs=srgb&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=6be89633a3b20429853f6d3192649709" data-object-fit="cover" /><div class="wp-block-cover__inner-container"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"black","textColor":"white","style":{"spacing":{"padding":{"top":"20px","bottom":"20px","left":"40px","right":"40px"}}},"fontSize":"medium"} -->
<div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-white-color has-black-background-color has-text-color has-background" style="padding-top:20px;padding-right:40px;padding-bottom:20px;padding-left:40px">Get Started</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover -->
```

</details>

If you paste that as-is into WordPress, it results in two 403 errors, trying to get URLs like `https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd19-20011.jpg?w=1200&amp;h=1200&amp;fit=clip&amp;crop=default&amp;dpr=1&amp;q=75&amp;vib=3&amp;con=3&amp;usm=15&amp;cs=srgb&amp;bg=F4F4F3&amp;ixlib=js-2.2.1&amp;s=6be89633a3b20429853f6d3192649709` — note the `&amp;`s.

If you replace `\u0026amp;` with `&` in the pattern, then paste it in, the URLs requested become like `https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pd19-20011.jpg?w=1200&h=1200&fit=clip&crop=default&dpr=1&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=6be89633a3b20429853f6d3192649709`, and these resolve successfully.

Props to @carolinan for flagging the issue.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #488 — As described there, sometimes images are saved with the ampersands multiply-encoded, resulting in strings like `…img.jpg?w=1200\u0026amp;h=1200\u0026amp;fit=clip`. When used in the editor, the first encoding is decoded, but then `…img.jpg?w=1200&amp;h=1200&amp;fit=clip` is not decoded, and causes a 403 error from rawpixel.

Additionally, sometimes the slash is stripped, leading to these URLs `…img.jpg?w=1200u0026amp;h=1200u0026amp;fit=clip`, which cause a block validation error.

This PR does a very simple string-replacement for these two cases, only on output. Looking for review to make sure this doesn't have any unexpected side effects.

I also removed `get_all_the_content`, it isn't used in this project after all.

### How to test the changes in this Pull Request:

1. Apply to your sandbox
2. Try copying this pattern: https://wordpress.org/patterns/pattern/step-by-step-process/
3. It should load with no validation error
4. Try copying this pattern: https://wordpress.org/patterns/pattern/shark-hero-banner/
5. The image should show up, with no 403 errors in the console
6. Make sure other patterns still work

Copy patterns using both copy buttons — the one on the single pattern page and in the grid view.

### CODE REVIEW

**Comment by StevenDufresne** [comment]
This is working as expected. 👍  

I'm not sure what's the best way to test but sometimes `&` are encoded to `&amp;`. 
That shouldn't cause any issues, right?

**Comment by ryelle** [comment]
> I'm not sure what's the best way to test but sometimes & are encoded to &amp;.

I think that's fine because they'll be decoded, the issue is the double-encoding of `\u0026amp;` — but we can see if there are still issues after this merges.

File: public_html/wp-content/plugins/pattern-directory/includes/pattern-post-type.php [hunk 1]
```diff
@@ -298,7 +298,7 @@ function register_rest_fields() {
 		'pattern_content',
 		array(
 			'get_callback' => function() {
-				return wp_kses_post( get_the_content() );
+				return decode_pattern_content( get_the_content() );
```
Comment (ntsekouras) [inline public_html/wp-content/plugins/pattern-directory/includes/pattern-post-type.php:301]: Do you think it's safe not to sanitize through `wp_kses_post` here? Check my comment: https://github.com/WordPress/gutenberg/issues/47636#issuecomment-1423783368

> The issue here is a result of GB sanitizing the pattern content through `wp_kses_post`. The flow there is:
- `wp_kses_normalize_entities` replaces `&` to `&amp;`
- `wp_pre_kses_block_attributes` replaces `&` to `\u0026` that results in `\u0026amp;` in the final output.

>The above though is for security reasons and normally is not an issue for block attributes that are not URLs. In the `Cover`
block case though it is a problem, as it results to a malformed URL.
